### ISSUE TITLE
question about post/comment history

### ISSUE THREAD

**Issue by mohrt** [arshadrr/subreddit-archiver#6]
If a post/comment gets updated/deleted, does the archive keep the history, or does it overwrite the saved data? tia

**Comment by arshadrr** [comment]
The tool is quite basic, once you save a few posts the only other things you can do is save more old posts (the "archive" command) or more new posts (the "update" command) than in the archive.

This means it does not do anything to posts (or comments) that are already saved.

If you want the newer version of posts or comments you will have to create a new archive. It does not have a feature that allows you to take an archive and make it reflect changes that were made to posts or comments since you saved them.
